/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Control.Controle;
import java.lang.ModuleLayer.Controller;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */

    private Controle c;
    
    public Janela() {
    initComponents();
    c = new Controle(this);
}

    public JButton getBt_0() {
        return bt_0;
    }

    public void setBt_0(JButton bt_0) {
        this.bt_0 = bt_0;
    }

    public JButton getBt_1() {
        return bt_1;
    }

    public void setBt_1(JButton bt_1) {
        this.bt_1 = bt_1;
    }

    public JButton getBt_2() {
        return bt_2;
    }

    public void setBt_2(JButton bt_2) {
        this.bt_2 = bt_2;
    }

    public JButton getBt_3() {
        return bt_3;
    }

    public void setBt_3(JButton bt_3) {
        this.bt_3 = bt_3;
    }

    public JButton getBt_4() {
        return bt_4;
    }

    public void setBt_4(JButton bt_4) {
        this.bt_4 = bt_4;
    }

    public JButton getBt_5() {
        return bt_5;
    }

    public void setBt_5(JButton bt_5) {
        this.bt_5 = bt_5;
    }

    public JButton getBt_6() {
        return bt_6;
    }

    public void setBt_6(JButton bt_6) {
        this.bt_6 = bt_6;
    }

    public JButton getBt_7() {
        return bt_7;
    }

    public void setBt_7(JButton bt_7) {
        this.bt_7 = bt_7;
    }

    public JButton getBt_8() {
        return bt_8;
    }

    public void setBt_8(JButton bt_8) {
        this.bt_8 = bt_8;
    }

    public JButton getBt_9() {
        return bt_9;
    }

    public void setBt_9(JButton bt_9) {
        this.bt_9 = bt_9;
    }

    public JButton getBt_clear() {
        return bt_clear;
    }

    public void setBt_clear(JButton bt_clear) {
        this.bt_clear = bt_clear;
    }

    public JButton getBt_divisao() {
        return bt_divisao;
    }

    public void setBt_divisao(JButton bt_divisao) {
        this.bt_divisao = bt_divisao;
    }

    public JButton getBt_multiplicacao() {
        return bt_multiplicacao;
    }

    public void setBt_multiplicacao(JButton bt_multiplicacao) {
        this.bt_multiplicacao = bt_multiplicacao;
    }

    public JButton getBt_resultado() {
        return bt_resultado;
    }

    public void setBt_resultado(JButton bt_resultado) {
        this.bt_resultado = bt_resultado;
    }

    public JButton getBt_soma() {
        return bt_soma;
    }

    public void setBt_soma(JButton bt_soma) {
        this.bt_soma = bt_soma;
    }

    public JButton getBt_subtracao() {
        return bt_subtracao;
    }

    public void setBt_subtracao(JButton bt_subtracao) {
        this.bt_subtracao = bt_subtracao;
    }

    public JTextField getTxt_input() {
        return txt_input;
    }

    public void setTxt_input(JTextField txt_input) {
        this.txt_input = txt_input;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bt_clear = new javax.swing.JButton();
        bt_0 = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        bt_divisao = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_subtracao = new javax.swing.JButton();
        bt_1 = new javax.swing.JButton();
        bt_soma = new javax.swing.JButton();
        bt_multiplicacao = new javax.swing.JButton();
        bt_resultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        txt_input.setBackground(new java.awt.Color(255, 255, 255));
        txt_input.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_input.setForeground(new java.awt.Color(0, 0, 0));
        txt_input.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_input.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        bt_clear.setBackground(new java.awt.Color(0, 0, 0));
        bt_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_clear.setForeground(new java.awt.Color(255, 255, 255));
        bt_clear.setText("C");
        bt_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_clearMouseClicked(evt);
            }
        });
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });

        bt_0.setBackground(new java.awt.Color(0, 0, 0));
        bt_0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_0.setForeground(new java.awt.Color(255, 255, 255));
        bt_0.setText("0");
        bt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_0ActionPerformed(evt);
            }
        });

        bt_9.setBackground(new java.awt.Color(0, 0, 0));
        bt_9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_9.setForeground(new java.awt.Color(255, 255, 255));
        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });

        bt_divisao.setBackground(new java.awt.Color(0, 0, 0));
        bt_divisao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_divisao.setForeground(new java.awt.Color(255, 255, 255));
        bt_divisao.setText("/");
        bt_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divisaoActionPerformed(evt);
            }
        });

        bt_7.setBackground(new java.awt.Color(0, 0, 0));
        bt_7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_7.setForeground(new java.awt.Color(255, 255, 255));
        bt_7.setText("7");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });

        bt_8.setBackground(new java.awt.Color(0, 0, 0));
        bt_8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_8.setForeground(new java.awt.Color(255, 255, 255));
        bt_8.setText("8");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });

        bt_4.setBackground(new java.awt.Color(0, 0, 0));
        bt_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_4.setForeground(new java.awt.Color(255, 255, 255));
        bt_4.setText("4");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_5.setBackground(new java.awt.Color(0, 0, 0));
        bt_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_5.setForeground(new java.awt.Color(255, 255, 255));
        bt_5.setText("5");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });

        bt_6.setBackground(new java.awt.Color(0, 0, 0));
        bt_6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_6.setForeground(new java.awt.Color(255, 255, 255));
        bt_6.setText("6");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        bt_2.setBackground(new java.awt.Color(0, 0, 0));
        bt_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_2.setForeground(new java.awt.Color(255, 255, 255));
        bt_2.setText("2");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_3.setBackground(new java.awt.Color(0, 0, 0));
        bt_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_3.setForeground(new java.awt.Color(255, 255, 255));
        bt_3.setText("3");
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });

        bt_subtracao.setBackground(new java.awt.Color(0, 0, 0));
        bt_subtracao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_subtracao.setForeground(new java.awt.Color(255, 255, 255));
        bt_subtracao.setText("-");
        bt_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_subtracaoActionPerformed(evt);
            }
        });

        bt_1.setBackground(new java.awt.Color(0, 0, 0));
        bt_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_1.setForeground(new java.awt.Color(255, 255, 255));
        bt_1.setText("1");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_soma.setBackground(new java.awt.Color(0, 0, 0));
        bt_soma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_soma.setForeground(new java.awt.Color(255, 255, 255));
        bt_soma.setText("+");
        bt_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_somaActionPerformed(evt);
            }
        });

        bt_multiplicacao.setBackground(new java.awt.Color(0, 0, 0));
        bt_multiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_multiplicacao.setForeground(new java.awt.Color(255, 255, 255));
        bt_multiplicacao.setText("x");
        bt_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_multiplicacaoActionPerformed(evt);
            }
        });

        bt_resultado.setBackground(new java.awt.Color(0, 0, 0));
        bt_resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_resultado.setForeground(new java.awt.Color(255, 255, 255));
        bt_resultado.setText("=");
        bt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bt_0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bt_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(bt_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_soma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
        // TODO add your handling code here:
        c.controleVar9();
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_clearMouseClicked

    }//GEN-LAST:event_bt_clearMouseClicked

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        // TODO add your handling code here:
        c.controleLimpar();
    }//GEN-LAST:event_bt_clearActionPerformed

    private void bt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_0ActionPerformed
        
        c.controleVar0();
    }//GEN-LAST:event_bt_0ActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed

        c.controleVar8();
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
        
        c.controleVar7();
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        
        c.controleVar4();
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
      
        c.controleVar5();
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
        
        c.controleVar6();
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        
        c.controleVar1();
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        
        c.controleVar2();
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
        
        c.controleVar3();
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_somaActionPerformed
        // TODO add your handling code here:
        c.controleSoma();
    }//GEN-LAST:event_bt_somaActionPerformed

    private void bt_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_subtracaoActionPerformed
        // TODO add your handling code here:
       c.controleSubtracao(); 
    }//GEN-LAST:event_bt_subtracaoActionPerformed

    private void bt_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_multiplicacaoActionPerformed
        // TODO add your handling code here:
        c.controleMultiplicacao();
    }//GEN-LAST:event_bt_multiplicacaoActionPerformed

    private void bt_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divisaoActionPerformed
        // TODO add your handling code here:
        c.controleDivisao();
    }//GEN-LAST:event_bt_divisaoActionPerformed

    private void bt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resultadoActionPerformed
        // TODO add your handling code here:
        c.controleResultado();
    }//GEN-LAST:event_bt_resultadoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_0;
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_divisao;
    private javax.swing.JButton bt_multiplicacao;
    private javax.swing.JButton bt_resultado;
    private javax.swing.JButton bt_soma;
    private javax.swing.JButton bt_subtracao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_input;
    // End of variables declaration//GEN-END:variables
}
